# This workflow will build a golang project for linux/arm64 architecture
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up environment variables
      run: |
        echo "GOOS=linux" >> $GITHUB_ENV
        echo "GOARCH=arm64" >> $GITHUB_ENV

    - name: Build
      run: |
        cd cmd
        go build -o mqtt

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        # Artifact name
        name: mochi_mqtt_aarch64
        # A file, directory or wildcard pattern that describes what to upload
        path: ./mqtt
